### ISSUE TITLE
[Feature] 분석결과 페이지 

### ISSUE THREAD

**Issue by jinnyleeis** [CEOS-PAT-PLATE/FrontEnd#14]
## 🔥 Issue
분석 결과 페이지 구현

#### 분석 페이지 메인 :  result[petId]/[dailymealId]
1.  //lib/apiService내  식단 저장 후에 -> 분석 진행할 수 있도록 하는 ' saveDailyMealsNutrients' 함수 구현 후 사용
-> 이유 : 분석 결과 페이지로 넘어갈 시엔, 아직, 식단에 대한 분석 요청을 하기 전일 수 있음 ->
반려견의 식사 내역 중 (부족, 과잉, 적정) 영양소 조회를 하기 위해선 /pet/${petId}/dailyMeals/nutrients 요청이 선행되어야하기 때문에, 
로컬 스토리지에 저장된 isDoneAlready의 불리언 값에 따라 분석 진행 api 요청 조건부로 수행함 

2. saveDailyMealsNutrients 수행 후   //lib/apiService내 fetchPetNutrientData 함수를 통해, 섭취 적정 칼로리 등 수치적 분석 결과 조회 api 요청을 promise.all로 한번에 수행함 
이에 대한 결과를 
todayNutrients: nutrientsResponse.data,
todayKcal: kcalResponse.data,
todaykcalRatio: kcalRatioResponse.data,
todayProperKcal: properKcalResponse.data,로 받아, 해당 함수에서 반환함 

3. fetchDailyMeals 함수 
결과 페이지에서도 201페이지에서와 같이, dailymeals 아이디에 따른 식사 내역 리스트를 하단에 표시해야 하므로, 
결과 페이지에 알맞은 selectedDate에 따른 식사 내역 fetch를 수행함 
로컬 스토리지에 selectedDate 의 값이 없을시, 오늘 식사 내역 fetch 요청 수행(201 페이지에서 -> 바로 result 페이지로 넘어간 경우)
이외에는, main/analyze 페이지에서, 특정 날짜 클릭 후, result 페이지로 넘어간 경우임 

####  분석 상세 페이지 : result[petId]/[dailymealId]/detail
1. 분석 페이지에서도 excessNutrients, properNutrients, deficientNutrients에 대한 정보를 promise.all를 통해 한번에 fetch함 
이때, peti와/dailymeal id가 필요한데, 이는 result 페이지내에서, Page({ params }: ResultProps)에서   
const { petId, dailyMealId } = params;를 통해 
selected-nutrient-${petId}-${dailyMealId}` 형태로 로컬 스토리지에 저장해 놓음 
-> 이 정보를 그래프의  props로 전달해 그래프 완성

#### 분석 추천 페이지 : result[petId]/[dailymealId]/recommend

1. 과잉 / 부족 영양소 개수를 navbar에 표시하기 위해 부족/과잉 영양소 조회 api 요청을 수행함 -> 이를 이용해 개수 표시
      const deficientCount = deficientNutrients.data.data.length
      const excessCount = excessNutrients.data.data.length

#### 분석 추천 페이지 중 부족 페이지 : result[petId]/[dailymealId]/recommend/deficientNutrients
1. nutrientAPI.getRecommendedSupplements(petId, dailyMealId); 부족 영양소별 추천 영양제 api 요청을 수행함 

#### 분석 추천 페이지 중 과잉 페이지 : result[petId]/[dailymealId]/recommend/excessiveNutrients

 1.  const response = await dailyMealsAPI.getExcessNutrients(petId, dailyMealId); 과잉 영양소 조회 api 요청을 수행함 

#### 기능 
1. 동적 라우팅을 통해, [petId]/[dailymealId]별로, 분석 페이지가 동적으로 구현될 수 있게끔 한다. 

2.  input-data2에서, -> confirm 모달을 통해 분석 결과페이지로 이동할시에는,
 오늘 날짜에 대한 분석 요청을 보내고, 오늘 날짜의 분석페이지로 이동할 수 있게끔한다. 

5. chart.js 라이브러리를 통해, Donaut 형태의 총 섭취 칼로리 그래프를 구현한다. 
chart.js 라이브러리를 통해, 영양소별 섭취 상태를 나타내는 bar 형태의 그래프들을 구현한다. 

6. 현재 조회하고있는 펫 정보에 따라, 동적으로 펫의 정보가 화면에 표시될 수 있게끔 구현한다. 

7. 결과 페이지 로딩 페이지를 next.js의 예약어인 loading.tsx를 이용해 구현한다. 

#### 기능 
chart.js 라이브러리를 사용해 9대 영양소에 대응되는 9개의 bar 그래프를 3개의 섹션으로 그룹화하여 하나의  LineChart 컴포넌트 재사용해 구현한다. 

기본 영양소 - group1/ 미네랄 - group2 / 비타민 - group3 를 props로 넘긴다. 

<ChartWrapper>
        <SectionTitle>기본 영양소</SectionTitle>
        <LineChart nutrientData={mainNutrients} group={1} />
        <SectionBorder />
        <SectionTitle>미네랄</SectionTitle>
        <LineChart nutrientData={mineralNutrients} group={2} />
        <SectionBorder />
        <SectionTitle>비타민</SectionTitle>
        <LineChart nutrientData={vitaminNutrients} group={3} />
</ChartWrapper>

#####  기능
recommend 폴더 내 layout.tsx를 통해, 부족 [부족 영양소 수] / 과잉 [과잉 영양소 수] 를 표시하는 Navbar를 구현해, 부족/과잉 영양소 페이지에서 공통으로 사용할 수 있게끔 한다. 

##### 기능 

1.  <NutrientInfoSection> 컴포넌트에 부족 영양소별 설명이 담길 수 있도록 구현한다. 
lib/nutrientDescription 파일내에, 
 nutritionDeficientInfo 배열에
영양소별로 영양소 특성과, 증상 텍스트를 관리한다.  -> 이를, NutrientInfoSection에서 불러온다. 
[ 
{ nutrientName: '단백질',
    title: '단백질',
    content:
      '',
    symptoms: {
        name: '성장 저하',
        description: '동일한 품종 / 나이의 다른 개들에 비해 작은 크기',
        src: 고관절,
      },
...}
,
]

2. <NutrientInfoSection> 컴포넌트 하단에, 부족 영양소별 추천 영양제 카드 컨테이너를 표시한다. 
next/image의 규정 (허용된 주소의 이미지만 불러오기 허용)을 피하기 위해, next.js의 image태그가 아닌, 기본 html 태그 img를 사용해,
영양소 사진을 표시한다.  :  src={supplement.drugImgPath}

3.   <RightArrow> 클릭 시, 영양제 상세 모달을 화면에 띄운다. 
영양제 상세 모달에서 별도의 api 요청을 하지 않고, 영양제 정보를 띄울 수 있도록, detail props를 통해 영양제 정보를 전달한다. 
  <RightArrow detail={{ supplement, nutrient: group.nutrientName }} /> 

##### 기능 
1. 부족 영양소와 동일하게 @lib/descriptionData에서 nutrientExcessInfo를 Import해와, 현재 과잉 영양소 관련 상세 정보를 표시한다. 
2. getNutritionAdvice 배열에 담긴 과잉 영양소별 주의사항 정보를 card에 담아 표시한다. 

## ✅ TODO - 남은 detail 추가 작업 
- [x] [분석결과 메인페이지, 상세 페이지]그래프 길이가 특정 길이 이상으로 늘어나지 않는 문제 (계속해서 잘림) 
- [x] [분석 결과/추천/과잉 영양소 페이지]과잉 영양소 상단에 '분석 결과' 텍스트 추가 
- [x] [all] 분석 결과페이지들 젼체적으로 뒤로 가기 버튼 추가하기 
- [x] [상세 페이지] 영양소별로 디자인 요청대로 그래프 색깔 맞추기
- [x] [상세 페이지,과잉/부족 영양소 페이지] 영양소 명사 받침에 따라 조사 맞추기 
- [x] [상세 페이지] 그래프내 섭취 영양소 소숫점 표기 가능하도록 하기 (현재 0.1g -> 0g으로 잘려서 표시)
- [x] [상세 페이지] 그래프에 적정 범위 표시 반영하기 (line-charts.tsx 컴포넌트 전체적으로 레이아웃 수정하기) 
- [x] [분석 결과 메인 페이지] 상단 박스 내 텍스트 부족영양소, 과잉 영양소 유무에 따라 조건부로 표시되는 텍스트 수정
- [x] [분석 결과 메인 페이지] 상단 박스 내 활동량 영어 말고, 한국어로 표시되도록 수정 
- [x] [상세 페이지] 상단의 흰색 박스 고정에서 -> 그래프 영역과 같이 scroll되도록 수정
- [x] [과잉 영양소 페이지] 강아지 > 반려견 어휘 수정
- [x] [과잉/부족 영양소 페이지] 과잉/부족 영양소 없을시, 텍스트말고, -> 귀여운 이미지 표시되도록 수정
