### ISSUE TITLE
[Feature] 인풋데이터2 - 하루식단 자연식 추가 기능 구현

### ISSUE THREAD

**Issue by jinnyleeis** [CEOS-PAT-PLATE/FrontEnd#7]
### 인풋데이터2 - 하루식단 자연식 추가 기능 구현

1. 검색어 입력 전 
- 최근에 먹은 자연식 카드들이 담긴 테이블 
- 가로 정렬, 오버플로우시  x축으로 스크롤 

2. 검색어 입력 중 
- 검색어에 맞게 필터링된 자연식 카드들이 담긴 테이블 
- 세로 정렬, 오버플로우시  y축으로 스크롤 

3. 자연식 카드 클릭 후 
- 클릭퇸 카드만 상단에 남고 카드 밑에는 섭취량 입력 컴포넌트 
- 입력중, 초록색 border line으로 포커싱 표시 

## ✅ TODO
- [x] 검색 페이지 전체 레이아웃 구현
- [x] 자연식 페이지 관련 더미 데이터와 db 참고해서 타입 인터페이스 추가
- [x] 자연식이 뭔지 모르겠어요 모달 구현 
- [x] 건의하기 버튼 구현
- [x] 검색 컴포넌트 구현 
- [x] 검색 컴포넌트 밑에 간략한 소개 텍스트 추가 
- [x] 테이블 컴포넌트 구현 (검색어 입력 전 / 입력 중에따라 달라지게)
- [x] 인풋 데이터 2 공통 Info 레이아웃 구현 
- [x] 저장 버튼 구현 
- [x] 검색 기능 client state 말고, URL search parameters로 리펙토링 하기 
- [x] 실제 api 연동
