### ISSUE TITLE
[Feature] 인풋 데이터 2 api + 남은 디테일 (due-date: 16일)

### ISSUE THREAD

**Issue by jinnyleeis** [CEOS-PAT-PLATE/FrontEnd#9]
# 🔥 Issue
### **1. 사용자 입력 -> 식단 추가기능 (자연식/포장간식/사료/즐겨찾기 페이지)**
_자연식 페이지의 로직은  포장간식+사료 페이지의 로직과 상이하므로, 식단 추가 api 요청 별도로 구현 필요_ 

### **2. 별표 -> 즐겨찾기 추가/해제 : 페이지별로 로직 상이** 
_자연식 페이지의 로직은  포장간식+사료 페이지의 로직과 상이하므로, 즐겨찾기 api 요청 별도로 구현 필요_ 

**a. 즐겨찾기 페이지**
- 기본값: 별표 active 상태 
- 재클릭시 즐겨찾기에서 삭제 요청

**b. 자연식/표장간식+사료 페이지**
- 기본값 : 별표 inactive 상태 
- form이 valid 할때, 별표 클릭시, 즐겨찾기에 추가 요청 
- from이 invalid 하면, 모달을 통한 form invalid하다는 모달 알림 구현 필요 

### **3. 추가된 식단을 리스트업하는 201 페이지**
- 추가된 하루 식단 조회 api 구현 
- 완료하기 클릭 시 분석 수정 불가 알림 모달에서 - [네] 클릭시, 분석 api 요청 & 분석 결과 페이지로 라우팅 
- 모달에서 x 클릭시 식단 입력 제거 요청 구현 (섭취사료 제거/섭취 자연식 제거/섭취포장간식 제거 / 섭취한 즐겨찾기된 자연식 제거 /섭취한 즐겨찾기된 사료제거 /섭취한 즐겨찾기된 포장간 제거 )

### 1. 공통 
- x : 뒤로 가기 버튼 (라우팅)
- 주의 알림 모달 (공통 컴포넌트 -레이아웃)
- 레이아웃 공통 컴포넌트 이용해서 (201 페이지 완료하기 /x) 주의 모달 별도로 구현하기 
- 유효성 검사 알림 + 즐겨찾기 추가 알림 (하단에) - 자연식/포장간식+사료 페이지 공통 컴포넌트 레이아웃 구현 
- 레이아웃 공통 컴포넌트 이용해서 유효성 검사 알림 / 즐겨찾기 추가 알림 별도의 컴포넌트로 재사용

### 2.자연식 페이지 
- 디자인 요청 사항 
- 자연식이 뭐에요 하위 밑줄 구현
- 밑줄 클릭시 자연식에 대한 설명 모달 구현

# ✅ TODO
- [x] 1. axios 세팅, index.ts - interceptor 추가 
- [x] 2. api 요청 만들기 
- [x] 3. 자연식/사료/간식 추가 페이지 - 리엑트 쿼리 이용한 커스텀 훅 작성 
- [x] 4. 즐겨찾기 페이지 관련 - 리엑트 쿼리 이용한 커스텀 훅 작성 
- [x] 5. 입력 데이터 recoil 전역 상태 로직 해결 
- [x] 6. [사료/간식페이지] api 요청 실 데이터로 변경 
- [x] 7. 자연식 카드 선택 디자인 요청 사항 반영 
- [x] 8. [자연식페이지] api 요청 실 데이터로 변경
- [x] 9. [즐겨찾기 페이지] 더미데이터로 -> api 요청 테스트
- [x] 10. [자연식페이지/사료+간식페이지] 별표 클릭 시 -> 즐겨찾기에 추가 api 요청 
- [x] 11.  [자연식페이지/사료+간식페이지] 별표 재클릭시 -> 즐겨찾기에서 제거 api 요청 
- [x] 12. [즐켜찾기 페이지] 별표 클릭된 상태에서 클릭 시 -> 즐겨찾기에서 제거 api 요청 
- [x] 13. [201 페이지] 추가한 식단 201 페이지에서 전체 조회 api 요청 
- [x] 14. [201 페이지] 모달 구현 
- [x] 15. [201 페이지] x -> 모달 -> 종료 클릭시, 식단 전체 제거 api 요청 
- [x] 16. 유효성 검사/즐겨찾기 알림 하단 컴포넌트 구현 
- [x] 17. 자연식이 뭐에요? 밑줄 + 자연식 뭐에요 설명 모달 
- [x] 18. 건의하기 버튼 구현 
- [x] 19. 완료하기 클릭시, [201 공통] 모달 -> 네 클릭시 분석 api 요청 & 분석 결과 페이지로 라우팅 

# 참고할만한 자료(선택)
